import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import useSound from 'use-sound'

import GruntButton from '../components/GruntButton'
import GoatButton from '../components/GoatButton'


export default function Home() {
  return (
    <div className={styles.container}>
      
      <Head>
      <title>Meeting Moods</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico"/>
      <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons"/>
      </Head>


      <main className={styles.main}>

        <h1 className={styles.title}>
          Cheer & Delight
        </h1>

        <div className={styles.grid}>

        <GruntButton/> 
        <GoatButton/>

        </div>

      </main>

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  )
}
