//Home page for Meeting Moods
//Created by Daniel McNamara - 2022

import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import useSound from 'use-sound';

import GoatButton from '../components/button-goat-scream';
import PartyButton from '../components/button-party-yay';


export default function Home() {
  return (
    <div className={styles.container}>
      
      <Head>
      <title>Meeting Moods</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.png"/>
      <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons"/>
      </Head>


      <main className={styles.main}>

        <h1 className={styles.title}>
        <span className={styles.green_highlight}>Cheer</span> & <span className={styles.yellow_highlight}>Delight</span><br/>for your next meeting
        </h1>

        <div className={styles.grid}>

        <PartyButton/> 
        <GoatButton/>

        </div>

      </main>

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  )
}
